    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: rg-cs-ansible
        name: "{{ instance_name }}"
        vm_size: Standard_DS1_v2
        admin_username: "{{ user }}"
        admin_password: "{{ password }}"
        network_interfaces: nic-cs-web
        os_type: Windows
        image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: 2019-Datacenter
          version: latest

